# fly.toml app configuration file generated for pokedexfullstack on 2024-01-03T13:15:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokedexfullstack"
primary_region = "ams"

[build]
  [build.args]
    NODE_VERSION = "18.12.1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "2s"
    path = "/version"

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "2s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"
